### ISSUE TITLE
Fix build for contrib PRs

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvec.org#105]
Build for contrib PRs, which don’t get secret env vars, is broken.

My hunch is the fix would be to run `pipenv run build` only on `master` just before `pipenv run deploy`

(One line change in .circleci/config.yml)

**Comment by honzajavorek** [comment]
Could someone try to contribute this from a fork so we know it fixes the problem? 😀

**Comment by encukou** [comment]
I guess I don't get exactly what you mean :(

**Comment by honzajavorek** [comment]
The CI doesn't provide contrib PRs with environment variables containing secrets. So now the build won't pass on contrib PRs, because it needs a token to reach Google Sheets. This would fix it and verify it works:

1. fork this repo to make a PR
2. change `.circleci/config.yml`
3. create the PR and see whether tests pass

I think the change could look as follows. This is what is there now:

```yaml
      - run:
          name: build data
          command: pipenv run build
      - run:
          name: run tests
          command: pipenv run test
      - run:
          name: build HTML
          command: pipenv run freeze
      - run:
          name: deploy
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              # https://github.com/pyvec/elsa/pull/65
              export TRAVIS=1
              export TRAVIS_REPO_SLUG=pyvec/pyvec.org
              # run Elsa
              pipenv run deploy
            fi
```

This is what could be a fix:

```yaml
      - run:
          name: run tests
          command: pipenv run test
      - run:
          name: deploy
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              pipenv run build
              pipenv run freeze

              # https://github.com/pyvec/elsa/pull/65
              export TRAVIS=1
              export TRAVIS_REPO_SLUG=pyvec/pyvec.org
              pipenv run deploy
            fi
```
